"""add language to posts

Revision ID: 9e9af48a37ab
Revises: fbfe0c4e4a93
Create Date: 2020-10-27 10:37:26.861272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9af48a37ab'
down_revision = 'fbfe0c4e4a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
